// export const ADD_TO_CART_REQUESTED= "ADD_TO_CART_REQUESTED";
// export const ADD_TO_CART_SUCCESSFULL= "ADD_TO_CART_SUCCESSFULL";
// export const ADD_TO_CART_ERRORED="ADD_TO_CART_ERRORED";

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_ONE_FROM_CART= "REMOVE_ONE_FROM_CART";
export const REMOVE_ALL_FROM_CART= "REMOVE_ALL_FROM_CART";
export const CLEAR_CART = "CLEAR_CART"; //Limpiar el carrito